apiVersion: v1
kind: Pod
metadata:
    name: using-secret-pod
spec:
    containers:
    - image: mongo
      name: using-secret-container
      command:
      - mongod
      volumeMounts:
      - name: testvol
        mountPath: /data/db
      env:
          - name: KRIYA
            valueFrom:
              secretKeyRef:
                name: secret1
                key: password
    volumes: 
        -  name: testvol
           hostPath:
             path: /newtestvol
